### ISSUE TITLE
What's the App in the last photo?

### ISSUE THREAD

**Issue by iridite** [roworu/nvidia-fedora-secureboot#1]
Can you please tell me the name of the App (Looks like Task Manager in Windows)in the last picture in README?

**Comment by roworu** [comment]
Hello, it named Mission Center:
https://missioncenter.io/
https://flathub.org/apps/io.missioncenter.MissionCenter

**Comment by iridite** [comment]
Thanks 👍

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
